version: '3'
services:
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=replicas_db"
    volumes:
      - ./master/data/db:/var/lib/mysql
      - ./master/data/backup:/home/backup
      - ./master/conf:/etc/mysql/conf.d
    links:
      - mysql-slave
    ports:
      - "3307:3306"
    restart: always
    hostname: mysql-master
  mysql-slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=replicas_db"
    volumes:
      - ./slave/data/db:/var/lib/mysql
      - ./slave/data/backup:/home/backup
      - ./slave/conf:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    restart: always
    hostname: mysql-slave

